---
abstract: 'Perform geographical queries using GeoNames Web Services'
author:
  - 'Per Henrik Johansen <per.henrik.johansen@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 6.48
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
keywords:
  - geo
  - geonames
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geo-GeoNames
no_index:
  directory:
    - t
    - inc
requires:
  JSON: 1.14
  Mojo::UserAgent: 0
  Test::More: 0.94
  XML::Simple: 2.13
  perl: 5.01
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Geo-GeoNames
  license: http://dev.perl.org/licenses/
  x_Metaspec:
    version: 2
version: 1.01
x_test_requires:
  Test::More: 0.94
