--- #YAML:1.0
name:               Geo-GeoNames
version:            0.09
abstract:           Perform geographical queries using GeoNames Web Services
author:
    - Per Henrik Johansen <per.henrik.johansen@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  6.48
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    JSON:         1.14
    LWP:          5.805
    perl:         5.008006
    Test::More:   0.94
    XML::Simple:  2.13
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/Bugs.html?Dist=Geo-GeoNames
    license:     http://dev.perl.org/licenses/
    repository:  git@github.com:briandfoy/geo-geonames.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:  []
test_requires:
    Test::More:  0.94
